### Guard::KonachaRails
#  available options:
#  - :run_all_on_start, defaults to true
#  - :notification, defaults to true
#  - :rails_environment_file, location of rails environment file,
#    should be able to find it automatically
guard 'konacha-rails' do
  # alter the next line if necessary e.g. if your js specs are coffee files
  watch(%r{^app/assets/javascripts/(.*)\.(js|coffee)?$}) { |m| "spec/javascripts/#{m[1]}_spec.js" }
  watch(%r{^(test|spec)/javascripts/.+_(test|spec)\.(js|coffee)$})
end
